favicon:
  mimetype: image/vnd.microsoft.icon
  path: 'public://error_1.ico'
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: 'public://icon.png'
  use_default: true
third_party_settings:
  shortcut:
    module_link: true
