favicon:
  mimetype: image/vnd.microsoft.icon
  path: 'public://error_0.ico'
  url: /themes/custom/test/favicon.ico
  use_default: 1
schemas:
  bootstrap: 8000
  test: 8000
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: 'public://logo.png'
  url: ''
  use_default: 0
cdn_theme: bootstrap
apply: Apply
reset_http_request_cache: ''
table: ''
